categories/urls.py
from unicodedata import category
from django.conf.urls import url
from .import views
from django.urls import path
from categories.views import CategoryUpdate, CategoryDelete

app_name = 'categories'

urlpatterns = [
    url(r'^$', views.category_list, name='list'),
    url(r'^create/$', views.category_create, name='create'),
    url(r'^edit/(?P<pk>\d+)$', CategoryUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CategoryDelete.as_view(), name='delete'),
]

django_part2/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from products import views as product_views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^categories/', include('categories.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^$', product_views.product_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
import imp
from django.conf.urls import url, include
from .import views
from products.views import ProductUpdate, ProductDelete
app_name = 'products'

urlpatterns = [
    url(r'^$', views.product_list, name='list'),
    url(r'^create/$', views.product_create, name='create'),
    url(r'^edit/(?P<pk>\d+)$', ProductUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', ProductDelete.as_view(), name='delete'),
]

categories/models.py
from urllib import request
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

products/models.py
from email.policy import default
from django.db import models
from categories.models import Category

# Create your models here.
class Product(models.Model):
    category = models.ForeignKey(Category, default=None, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    price = models.FloatField()
    quantity = models.IntegerField()
    sku = models.CharField(max_length=50)
    picture = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.description[:20] + '...'

categories/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .import models

class CreateCategory(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = ['title']

products/forms.py
from django import forms
from .import models

class CreateProduct(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['category', 'title', 'description', 'price', 'quantity', 'sku', 'picture']

class EditProduct(forms.ModelForm):
        model = models.Product
        fields = ['category', 'title', 'description', 'price', 'quantity', 'sku', 'picture']

categories/views.py
from dataclasses import field
from pyexpat import model
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Category
from .import forms

# Create your views here.
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category_list.html', {'categories': categories})

def category_create(request):
    if request.method == 'POST':
        form = forms.CreateCategory(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('categories:list') 
    else:
        form = forms.CreateCategory()
    return render(request, 'category_create.html', {'form':form})

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
   
class CategoryUpdate(UpdateView):
    model = Category
    fields = ['title']
    success_url = reverse_lazy('categories:list')

class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('categories:list')

django_part2/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login

def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('products:list')            
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

products/views.py
from django.shortcuts import render, redirect
from .models import Product
from .import forms


# Create your views here.
def product_list(request):
    products = Product.objects.all()
    return render(request, 'product_list.html', {'products': products})

def product_create(request):
    if request.method == 'POST':
        form = forms.CreateProduct(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('products:list') 
    else:
        form = forms.CreateProduct()
    return render(request, 'product_create.html', {'form':form})

from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
   
class ProductUpdate(UpdateView):
    model = Product
    fields = ['category', 'title', 'description', 'price', 'quantity', 'sku', 'picture']
    success_url = reverse_lazy('products:list')

class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('products:list')

categories/templates/categories/category_confirm_delete.html
<h1>Delete Category</h1>
<form method="post">
  {% csrf_token %} Are you sure you want to delete this category:
  <em><strong>{{ category.title }} </strong></em><br />
  <input type="submit" value="Yes, Delete" />
</form>
<a href="{% url 'categories:list' %}">No, Go Back</a>

categories/templates/categories/category_form.html
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

categories/templates/category_create.html
{% extends 'base_layout.html' %} {% block content %}

<div class="create_category">
  <h2>Create a New Category</h2>
  <form class="site-form" action="{% url 'categories:create' %}" method="post">
    {% csrf_token %} {{ form }}
    <input type="submit" value="Create" />
  </form>
</div>

{% endblock %}

categories/templates/category_list.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Category List</h1>

{% if user.is_authenticated %}
<a
  class="btn btn-primary btn-md"
  tabindex="-1"
  role="button"
  aria-disabled="true"
  href="{% url 'categories:create' %}"
  >Add New Category</a
>
{% else %}
<a href="{% url 'login' %}">Log In</a> {% endif %}

<div class="categories">
  <div class="category">
    <table class="table">
      {% for category in categories %}
      <tr>
        <td>{{ category.title }}</td>
        {% if user.is_authenticated %}
        <td>
          <a
            class="btn btn-warning btn-sm"
            href="{% url 'categories:edit' category.id %}"
            >Edit</a
          >
          <a
            class="btn btn-danger btn-sm"
            href="{% url 'categories:delete' category.id %}"
            >Delete</a
          >
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock content %}

products/templates/product_create.html
{% extends 'base_layout.html' %} {% block content %}

<div class="create_product">
  <h2>Create a New Product</h2>
  <form
    class="site-form"
    action="{% url 'products:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{ form }}
    <input type="submit" value="Create" />
  </form>
</div>

{% endblock %}

products/templates/product_list.html
{% extends 'base_layout.html' %} {% block content %}

<h1>Product List</h1>

{% if user.is_authenticated %}
<a
  class="btn btn-primary btn-md"
  tabindex="-1"
  role="button"
  aria-disabled="true"
  href="{% url 'products:create' %}"
  >Add New Product</a
>
{% else %}
<a class="btn btn-primary btn-md" href="{% url 'login' %}">Log In</a>
{% endif%}

<div class="products">
  <div class="product">
    <div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Thumb</th>
            <th scope="col">Category</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            <th scope="col">SKU</th>
            {% if user.is_authenticated %}
            <th scope="col">Operation</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
          <tr>
            <td><img src="{{product.picture.url}}" style="width: 80px" /></td>
            <td>{{ product.category }}</td>
            <td>{{ product.title }}</td>
            <td>{{ product.description }}</td>
            <td>${{ product.price }}</td>
            <td>{{ product.sku }}</td>
            {% if user.is_authenticated %}
            <td>
              <a
                class="btn btn-warning btn-sm"
                href="{% url 'products:edit' product.id %}"
                >Edit</a
              >
              <a
                class="btn btn-danger btn-sm"
                href="{% url 'products:delete' product.id %}"
                >Delete</a
              >
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content %}

products/templates/products/product_confirm_delete.html
<h1>Delete Prodcut</h1>
<form method="post">
  {% csrf_token %} Are you sure you want to delete this product:
  <em><strong>{{ product.title }} </strong></em><br />
  <input type="submit" value="Yes, Delete" />
</form>
<a href="{% url 'products:list' %}">No, Go Back</a>

products/templates/products/product_form.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Part2 Wei Li</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css'%}"></link>
  </head>
  <body>
    <header class="wrapper">
      <h1 class="text-center"><a class="link-dark" href="{% url 'home' %}">Django Part2 Wei Li</a></h1>
    </header>
  </body>
  <div class="wrapper">{% block content%} {% endblock %}</div>
</html>

templates/login.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Log In</h1>
<form class="site-form" action="{% url 'login' %}" method="post">
  {% csrf_token %} {{ form }} {% if request.GET.next %}
  <input type="hidden" name="next" value="{{request.GET.next}}" />
  {%endif%}
  <input type="submit" value="Login" />
</form>
{% endblock %}